### PR TITLE
(BKR-1590) Support new yum and apt release locations

### PR DESCRIPTION
**Pull request by treydock**

### CODE REVIEW

**Comment by treydock** [comment]
Tested with a few of my modules and verified that using something like `BEAKER_PUPPET_COLLECTION=puppet6` results in this:

```
centos-7 10:44:41$ rpm --replacepkgs -Uvh http://yum.puppet.com/puppet6-release-el-7.noarch.rpm 
  warning: /var/tmp/rpm-tmp.niMwWy: Header V4 RSA/SHA256 Signature, key ID ef8d349f: NOKEY
  Retrieving http://yum.puppet.com/puppet6-release-el-7.noarch.rpm
  Preparing...                            ########################################
  Updating / installing...
  puppet6-release-6.0.0-4.el7             ######################  ###########  ####  #  #  #

```

**Comment by kevpl** [comment]
jenkins, test this please

**Comment by mmack000** [comment]
How do you get rpm -Uvh https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm

**Comment by treydock** [comment]
Those were moved to archive URL: https://groups.google.com/forum/#!msg/puppet-users/cCsGWKunBe4/OdG0T7LeDAAJ, this PR just addressed the still supported versions.

**Pull request merged**
