### PR TITLE
(BKR-1510) make fact helpers support structured facts

### PR DESCRIPTION
**Pull request by sevendials**
This code adds json to the options of fact_on() and parses the result. This means that fact() and fact_on() preserve the structure and data types of facts.

### CODE REVIEW

**Comment by mchllweeks** [comment]
jenkins test this please

**Comment by sevendials** [comment]
@mchllweeks I run rake test:spec:run locally and get this:
```
Finished in 3.33 seconds (files took 0.81633 seconds to load)
274 examples, 0 failures
```
I can't see the Jenkins result details on this PR other than it is failing. Should I be running some other test?

**Comment by mchllweeks** [comment]
@sevendials Here is the error from Jenkins:
09:49:45 Failures:
09:49:45 
09:49:45   1) ClassMixedWithDSLHelpers#fact_on preserves data types
09:49:45      Failure/Error: expect(structured_fact['uid'].class).to be Integer
09:49:45 
09:49:45        expected #<Class:18330360> => Integer
09:49:45             got #<Class:18330200> => Fixnum
09:49:45 
09:49:45        Compared using equal?, which compares object identity,
09:49:45        but expected and actual are not the same object. Use
09:49:45        `expect(actual).to eq(expected)` if you don't care about
09:49:45        object identity in this example.
09:49:45 
09:49:45 
09:49:45        Diff:
09:49:45        @@ -1,2 +1,2 @@
09:49:45        -Integer
09:49:45        +Fixnum
09:49:45      # ./spec/beaker-puppet/helpers/facter_helpers_spec.rb:66:in `block (3 levels) in <top (required)>'
09:49:45 
09:49:45 Finished in 2.44 seconds (files took 1.35 seconds to load)
09:49:45 336 examples, 1 failure
09:49:45 
09:49:45 Failed examples:
09:49:45 
09:49:45 rspec ./spec/beaker-puppet/helpers/facter_helpers_spec.rb:61 # ClassMixedWithDSLHelpers#fact_on preserves data types

**Comment by sevendials** [comment]
@mchllweeks I couldn't find any docs about appropriate Ruby versions but I'm guessing that Jenkins is using Ruby <2.4 because above that, Fixnum is deprecated.

I've rebased and pushed a fix to it.

**Comment by mchllweeks** [comment]
jenkins test this please

**Comment by mchllweeks** [comment]
jenkins re-test this please

**Pull request merged**
