### PR TITLE
make install_package cmdline_args parameter part of…

### PR DESCRIPTION
**Pull request by DarkGigaByte**
...install_puppet_agent_on options.

### CODE REVIEW

**Comment by mchllweeks** [comment]
@DarkGigaByte Please add a test to make sure we don't break this fix in the future.

**Comment by DarkGigaByte** [comment]
Won't have the time in the next couple weeks. Maybe someone else will do it in the meantime?

**Comment by mchllweeks** [comment]
last comment current

**Comment by kevpl** [comment]
last comment still current. If progress isn't made in a week, we'll close this due to inactivity

**Comment by kevpl** [comment]
closing due to inactivity.

**Pull request closed without merging**
